## Create Volume using below command ##
#gcloud compute disk create --size=15Gi --zone=ap-south1-a my-data-disk 

---
## Persistent Volume ##
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 15Gi 
  storageClassName: slow    
  gcePersistentDisk:
    fsType: ext4
    pdName: my-data-disk
    readOnly: false
  persistentVolumeReclaimPolicy: Retain



---
## Storage Class Wordpress ##
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-pv
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
